import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import VercelButton from "https://framer.com/m/VercelButton-Au0U.js@IXa0oIEt13Z3NLhCXlBj"
import Friendship from "https://framer.com/m/Friendship-2bOP.js@qjZrjvFgokYlJ32b1GI7"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Friendship />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
